version: '3.8'

services:
  assethub-ml:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assethub-ml-service
    restart: unless-stopped
    environment:
      - API_BASE_URL=http://host.docker.internal:5168
      - DB_SERVER=db32354.public.databaseasp.net
      - DB_NAME=db32354
      - DB_USER=db32354
      - DB_PASSWORD=9y-P!Bt8e6R@
      - MODEL_PATH=models/xgboost_asset_health.json
      - RUN_ONCE=false
      - BATCH_CRON_HOUR=2
      - BATCH_CRON_MINUTE=0
      - TRAIN_CRON_DAYS=1,15
      - TRAIN_CRON_HOUR=3
      - TRAIN_CRON_MINUTE=0
    volumes:
      - .:/app
      - ./models:/app/models
    extra_hosts:
      - "host.docker.internal:host-gateway"
