# Redirección global HTTP a HTTPS
server {
    listen 80;
    server_name assetshub.dev.sonnora.mx api.dev.sonnora.mx;
    return 301 https://$host$request_uri;
}

# Redirige el tráfico web de la app (Frontend)
server {
    listen 443 ssl http2;
    server_name assetshub.dev.sonnora.mx;

    # --- CONFIGURACIÓN SSL (Ajustar rutas a donde realmente estén los certificados en el contenedor) ---
    ssl_certificate /etc/letsencrypt/live/dev.sonnora.mx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.sonnora.mx/privkey.pem;
    
    # Opciones de seguridad recomendadas
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://10.0.0.6:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_addrs;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Redirige el tráfico de la API (Backend)
server {
    listen 443 ssl http2;
    server_name api.dev.sonnora.mx;

    # --- CONFIGURACIÓN SSL (Ajustar rutas a donde realmente estén los certificados en el contenedor) ---
    ssl_certificate /etc/letsencrypt/live/dev.sonnora.mx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.sonnora.mx/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://10.0.0.6:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_addrs;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
